import Header from "./Header";
import Providers from "./providers";

import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from 'react';
import { getServerSession } from "next-auth/next";
import { authOptions } from "../auth/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}